INSERT INTO FILTERS (ID, NAME, SELECTION) VALUES (1, 'First Filter', 1);
INSERT INTO FILTERS (ID, NAME, SELECTION) VALUES (2, 'Second Filter', 2);
INSERT INTO CRITERIES (ID, TYPE, CONDITION, VALUE, FILTER_ID) VALUES (3, 'AMOUNT', 'MORE', '4', 1);
INSERT INTO CRITERIES (ID, TYPE, CONDITION, VALUE, FILTER_ID) VALUES (4, 'TITLE', 'STARTS_WITH', 'Meow', 2);
INSERT INTO CRITERIES (ID, TYPE, CONDITION, VALUE, FILTER_ID) VALUES (5, 'DATE', 'FROM', '2021-10-25', 2);
